[pytest]
# PEP 657: tracebacks
addopts = 
    --tb=short
    -v
    --cov=supply
    --cov-report=term-missing
    --cov-report=html:reports/coverage
    --cov-fail-under=90
    --cov-config=.coveragerc

# Ruta de tests
testpaths = tests

# Directorio raiz al PYTHONPATH
pythonpath = .